### ISSUE TITLE
Hello Sir.

### ISSUE THREAD

**Issue by Chaleeshadow** [seelebrn/XiakeENMOD#1]
Hello sir, I trying make ModTranslate Volcano Princess for my language, By learning from your code.
I have a problem with assigning a KV with the tag color. Could you please provide some guidance or suggestions to help me?

```
//ChatDicKV.txt
It's been decided.¤ตัดสินใจแล้วล่ะ
Then...¤ต่อจากนี้...
Together with *…& live a happy ever after.¤จะใช้ชีวิตที่เหลืออยู่กับ*…& อย่างมีความสุข
I heard <color=#3767ff>Asbel</color> turned down the offer from the Royals, and insisted on killing those magical beasts by himself.¤ฉันได้ยินว่า <color=#3767ff>อัสเบล</color> ปฏิเสธข้อเสนอจากราชวงศ์และยืนกรานที่จะฆ่าสัตว์วิเศษเหล่านั้นด้วยตัวเขาเอง
```
```
//Plugin.cs 
		public static Dictionary<string, string> FileToDictionary(string dir)
		{
			Dictionary<string, string> dictionary = new Dictionary<string, string>();
			IEnumerable<string> enumerable= File.ReadLines(Path.Combine(assemblyFolder, "Translations", dir));
			foreach (string text in enumerable)
			{
				string[] array = text.Split(new char[]
				{
					'¤'
				});
				bool flag = array[0] != array[1];
				if (flag)
				{
					KeyValuePair<string, string> keyValuePair = new KeyValuePair<string, string>(Regex.Replace(array[0], "\\t|\\n|\\r", ""), array[1]);
					bool flag2 = !dictionary.ContainsKey(keyValuePair.Key);
					if (flag2)
					{
						dictionary.Add(keyValuePair.Key, keyValuePair.Value);
					}
				}
			}
			return dictionary;
		} 

                [HarmonyPatch(typeof(DataSys), "InitializeData")]
                [HarmonyPostfix]
                private static void InitializeDataPostfix(ref DataSys __instance)
                {
                    Plugin.translationDict = Plugin.FileToDictionary("ChatDicKV.txt");
                    foreach (var entry in __instance.dataCfg.chatDic)
                    {
                        foreach (var chats in entry.Value)
                        {
                            foreach (var chat in chats)
                            {
                                if (chat.content != null && Plugin.translationDict.ContainsKey(chat.content))
                                {
                                    Plugin.log.LogMessage(Plugin.translationDict[chat.content]);
                                    chat.content = Plugin.translationDict[chat.content];
                                    Plugin.log.LogMessage(chat.content);
                                }
                            }
                        }
                    }
              }
```

**Comment by seelebrn** [comment]
Hey, 
Thanks for reaching out. Tbh, this code is still a draft and I must work on it more, which I'll do when I have time. 
But what is the issue in your case ? In what way do you have trouble with color tags ? 
Could you confirm the patched method indeed calls the exact original string which is in your dict ?

**Comment by Chaleeshadow** [comment]
I apologize for the confusion, I trying to make Mod Game  Volcano Princess
"In what way do you have trouble with color tags ?"
Yes i have trouble only with color tags, It seems that can't assign KV from dict 

![](https://i.imgur.com/OTwn7eIaf.jpeg) 
```
It's been decided.¤ตัดสินใจแล้วล่ะ
```
![](https://i.imgur.com/V2QXHzMdq.jpeg)
```
I heard <color=#3767ff>Asbel</color> turned down the offer from the Royals, and insisted on killing those magical beasts by himself.¤ฉันได้ยินว่า {color=#3767ff}อัสเบล{/color} ปฏิเสธข้อเสนอจากราชวงศ์และยืนกรานที่จะฆ่าสัตว์วิเศษเหล่านั้นด้วยตัวเขาเอง
```

**Comment by seelebrn** [comment]
Could you tell me the output for Plugin.log.LogMessage(chat.content);, if any ? 
Since I suppose it's likely there's none, could you try to Plugin.log.LogMessage(chat.content); before " if (chat.content != null && Plugin.translationDict.ContainsKey(chat.content))" and tell me the result ? Especially if you find said string.

My reasoning is as follows : if this string is not matched, I suppose (but I may be wrong) that at the time you're patching, the string is in a different state, the color tag is either not here yet or already has been processed/modified. Hence my question. 

Thank you !

**Comment by Chaleeshadow** [comment]
It seems that I made a mistake thinking it was due to the color tags, but in reality, it's because it can't read the KV:laughing:
Now I can log KV on it. Thank you for the response you are my hero!!:+1:
![s](https://i.imgur.com/zhIoJBwha.png)

**Comment by seelebrn** [comment]
Perfect and thank you ! Good luck with your modding projects !
